fix: replacing function ingress with service ingress in vpc-sample
GoogleCloudPlatform/cloud-run-samples pull request #198
Opened 2023-07-15 06:28 UTC by pattishin

**Issue:** Per b/290374799.

2023-07-17 19:14 UTC, pattishin commented
/gcbrun

2023-07-17 19:16 UTC, pattishin commented
/gcbrun

2023-07-17 19:18 UTC, pattishin commented
/gcbrun

2023-07-17 20:29 UTC, pattishin commented
/gcbrun

2023-07-18 06:53 UTC, pattishin commented
/gcbrun

2023-07-18 18:29 UTC, muncus approved these changes

2023-07-18 18:29 UTC, muncus commented on vpc-sample/run/README.md
> +The Cloud Run sends a get request via the VPC connector to the network-restricted service.
```suggestion
This Cloud Run service sends a get request via the VPC connector to the network-restricted service.
```

2023-07-18 22:40 UTC, averikitsch requested changes

2023-07-18 22:40 UTC, averikitsch commented on vpc-sample/run/README.md
> +* Serverless VPC Access API
```suggestion
* Serverless VPC Access
* Cloud Build
```

2023-07-18 22:40 UTC, averikitsch commented on vpc-sample/run/README.md
> +From inside the `vpc-sample/run-ingress` directory:
```suggestion
From inside the `vpc-sample/run/run-egress` directory:
```

2023-07-18 22:40 UTC, averikitsch commented on vpc-sample/run/README.md
> +```
The prior setup used the Dockerfile in the functions directory to deploy to cloud run instead of duplicating a hello world app.

2023-07-26 21:29 UTC, pattishin commented
/gcbrun

2023-08-21 20:52 UTC, bobfuru commented on vpc-sample/run/README.md
> +## Set your environment up
```suggestion
## Set up your environment
```

2023-08-21 20:52 UTC, bobfuru commented on vpc-sample/run/README.md
> +## Deploy the Cloud Run service (egress) with a vpc connector
```suggestion
## Create Serverless VPC Access connector

```sh
gcloud compute networks vpc-access connectors create serverless-connector \
    --region=${REGION} \
    --range=10.8.0.0/28
```

## Deploy the restricted Cloud Run Service (ingress only)

From inside the `vpc-sample/run/run-ingress` directory:

```sh
gcloud run deploy restricted-service \
    --source=. \
    --ingress=internal \
    --no-allow-unauthenticated
```

The `-ingress=internal` will restrict access to this Cloud Run services to other services inside the project.
To call this service, deploy another Cloud Run service with the egress going through a VPC connector.


## Deploy the Cloud Run service (egress) with a VPC connector
```

2023-09-26 22:18 UTC, pattishin commented
Switching to different solution, closing out.

2023-09-26 22:18 UTC, closed without merging