feat: hello php nginx sample (multi-containers) 🚧
GoogleCloudPlatform/cloud-run-samples pull request #199
Opened 2023-07-22 01:41 UTC by pattishin

Still WIP, hold off on reviewing.

2023-07-25 18:37 UTC, pattishin commented
/gcbrun

2023-07-25 18:39 UTC, pattishin commented
/gcbrun

2023-07-25 20:51 UTC, pattishin commented
/gcbrun

2023-07-26 22:57 UTC, pattishin commented
@JulienBreux When you have time to review, would love your feedback!

2023-07-27 08:03 UTC, JulienBreux requested changes
Very good quality work!
We're delighted to be able to offer the PHP community a fine example of Cloud Run.
Big thanks!

2023-07-27 08:03 UTC, JulienBreux commented on multi-container/hello-php-nginx-sample/php-app/index.php
> +# [END cloudrun_mc_hello_php_nginx_sidecar_index]
```suggestion
<?php
// [START cloudrun_mc_hello_php_nginx_sidecar_index]

echo 'This is main php app. Hello PHP World!';

phpinfo();

// [END cloudrun_mc_hello_php_nginx_sidecar_index]
```

As above :)

2023-07-28 19:38 UTC, pattishin commented
Since this is not lang agnostic, moving to `php-docs-samples`. 
https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1901

Closing out here.

2023-07-28 19:38 UTC, closed without merging